services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=vedpandey
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=persona_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
